name: Test Embold Action

on:
  push:
    branches: [ github_action_java ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test Embold Action
        uses: embold/embold-github-action@v1_master
        with:
          emboldUrl: https://demo.embold.io/
          emboldToken: ${{ secrets.EMBOLD_TOKEN_DEMO_INST }}
          emboldRepoUid: 81aba9b3940bbf35aac36dd3e4a45562
          repositoryConfigPath: repository-configuration.json
          downloadConfig: 'true'
