name: Embold Scan - Java

on:
  push:
    branches: [main]
    paths:
      - 'sample_source_code/java/**'
  workflow_dispatch:

jobs:
  embold-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Embold Scan
        id: embold-scan
        uses: embold/github-action-docker@v2.0.0
        with:
          emboldUrl: https://demo.embold.io/
          emboldToken: ${{ secrets.EMBOLD_TOKEN_DEMO_INST }}
          emboldRepoUid: 034560c4e627f02cc243e7d3eddc7d18
          repositoryConfigPath: repository-configuration.json
          downloadConfig: 'true'
          qualityGate: 'true'
          snapshotLabel: ${{ github.run_number }}

      - name: Check Quality Gate Result
        if: steps.embold-scan.outputs.qualityGateStatus == 'FAILED'
        run: |
          echo "Quality gate failed!"
          exit 1
