name: Build and Test

on:
  push:
    branches:
      - github_action_cpp
  pull_request:
    branches:
      - github_action_cpp

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-9
          pip install gcovr==8.2

      - name: Configure CMake
        run: |
          cd sample_source_code/CPP/googletest
          g++ --version
          gcov --version
          gcovr --version
          cmake . -DCMAKE_CXX_FLAGS="-g -O0 -fprofile-arcs -ftest-coverage" \
                -DCMAKE_BUILD_TYPE=Debug \
                -Dgtest_build_samples=ON \
                -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build with Make
        run: |
          cd sample_source_code/CPP/googletest
          make

      - name: Run GoogleTest and Generate XML Report
        run: |
          cd sample_source_code/CPP/googletest
          mkdir -p output/gtest
          ./googletest/sample1_unittest \
              --gtest_output=xml:./output/gtest/gtest1.xml
          cat ./output/gtest/gtest1.xml

      - name: Generate Code Coverage Report (gcovr)
        run: |
          cd sample_source_code/CPP/googletest
          rm -rf ./output/gcov
          mkdir -p ./output/gcov
          gcovr -r . --xml -o ./output/gcov/gcov1.xml

      - name: Download and Unpack BrowserStack CQ Scanner
        run: |
          curl https://v1.embold.io/nfs/CLI/browserstack-codequality-scanner.tar.gz -o browserstack-codequality-scanner-archive.tar.gz
          tar xvf browserstack-codequality-scanner-archive.tar.gz
        
      - name: Run Static Code Analysis
        continue-on-error: true
        env:
          EMBOLD_TOKEN: ${{ secrets.EMBOLD_TOKEN_DEMO_INST }}
        run: |
          ./browserstack-codequality-scanner/bin/embold-scanner analyse \
          -u https://demo.embold.io/ \
          -t $EMBOLD_TOKEN \
          -r f3ff1a57484e656e27b2475bcf9f5d9b \
          -c sample_source_code/JAVA/commons-lang/repository-configuration.json \
          -qg
