name: Build and Test

on:
  push:
    branches:
      - github_action_cpp
  pull_request:
    branches:
      - github_action_cpp

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ gcovr lcov

      - name: Configure CMake
        run: |
          cmake -S sample_source_code/CPP/googletest -B build \
                -DCMAKE_CXX_FLAGS="-g -O0 -fprofile-arcs -ftest-coverage" \
                -DCMAKE_BUILD_TYPE=Debug \
                -Dgtest_build_samples=ON \
                -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build with Make
        run: make -C build -j$(nproc)

      - name: Run GoogleTest and Generate XML Report
        run: |
          mkdir -p output/gtest
          sample_source_code/CPP/googletest/build/googletest/sample1_unittest \
              --gtest_output=xml:./output/gtest/gtest1.xml

      - name: Generate Code Coverage Report (gcovr)
        run: |
          rm -rf ./output/gcov
          mkdir -p ./output/gcov
          gcovr -r sample_source_code/CPP/googletest --xml -o ./output/gcov/gcov1.xml

      - name: Upload Test and Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-results
          path: output/
